//go:build !ignore_autogenerated

/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	appsv1 "k8s.io/api/apps/v1"
	corev1 "k8s.io/api/core/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterComponentDefinition) DeepCopyInto(out *ClusterComponentDefinition) {
	*out = *in
	if in.ConfigSpecs != nil {
		in, out := &in.ConfigSpecs, &out.ConfigSpecs
		*out = make([]ComponentConfigSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ScriptSpecs != nil {
		in, out := &in.ScriptSpecs, &out.ScriptSpecs
		*out = make([]ComponentTemplateSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Probes != nil {
		in, out := &in.Probes, &out.Probes
		*out = new(ClusterDefinitionProbes)
		(*in).DeepCopyInto(*out)
	}
	if in.LogConfigs != nil {
		in, out := &in.LogConfigs, &out.LogConfigs
		*out = make([]LogConfig, len(*in))
		copy(*out, *in)
	}
	if in.PodSpec != nil {
		in, out := &in.PodSpec, &out.PodSpec
		*out = new(corev1.PodSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Service != nil {
		in, out := &in.Service, &out.Service
		*out = new(ServiceSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.StatelessSpec != nil {
		in, out := &in.StatelessSpec, &out.StatelessSpec
		*out = new(StatelessSetSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.StatefulSpec != nil {
		in, out := &in.StatefulSpec, &out.StatefulSpec
		*out = new(StatefulSetSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.ConsensusSpec != nil {
		in, out := &in.ConsensusSpec, &out.ConsensusSpec
		*out = new(ConsensusSetSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.ReplicationSpec != nil {
		in, out := &in.ReplicationSpec, &out.ReplicationSpec
		*out = new(ReplicationSetSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.HorizontalScalePolicy != nil {
		in, out := &in.HorizontalScalePolicy, &out.HorizontalScalePolicy
		*out = new(HorizontalScalePolicy)
		**out = **in
	}
	if in.SystemAccounts != nil {
		in, out := &in.SystemAccounts, &out.SystemAccounts
		*out = new(SystemAccountSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.VolumeTypes != nil {
		in, out := &in.VolumeTypes, &out.VolumeTypes
		*out = make([]VolumeTypeSpec, len(*in))
		copy(*out, *in)
	}
	if in.CustomLabelSpecs != nil {
		in, out := &in.CustomLabelSpecs, &out.CustomLabelSpecs
		*out = make([]CustomLabelSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.SwitchoverSpec != nil {
		in, out := &in.SwitchoverSpec, &out.SwitchoverSpec
		*out = new(SwitchoverSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.PostStartSpec != nil {
		in, out := &in.PostStartSpec, &out.PostStartSpec
		*out = new(PostStartAction)
		(*in).DeepCopyInto(*out)
	}
	if in.VolumeProtectionSpec != nil {
		in, out := &in.VolumeProtectionSpec, &out.VolumeProtectionSpec
		*out = new(VolumeProtectionSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.ComponentDefRef != nil {
		in, out := &in.ComponentDefRef, &out.ComponentDefRef
		*out = make([]ComponentDefRef, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ServiceRefDeclarations != nil {
		in, out := &in.ServiceRefDeclarations, &out.ServiceRefDeclarations
		*out = make([]ServiceRefDeclaration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Exporter != nil {
		in, out := &in.Exporter, &out.Exporter
		*out = new(Exporter)
		**out = **in
	}
	if in.Monitor != nil {
		in, out := &in.Monitor, &out.Monitor
		*out = new(MonitorConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterComponentDefinition.
func (in *ClusterComponentDefinition) DeepCopy() *ClusterComponentDefinition {
	if in == nil {
		return nil
	}
	out := new(ClusterComponentDefinition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterDefinition) DeepCopyInto(out *ClusterDefinition) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterDefinition.
func (in *ClusterDefinition) DeepCopy() *ClusterDefinition {
	if in == nil {
		return nil
	}
	out := new(ClusterDefinition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClusterDefinition) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterDefinitionList) DeepCopyInto(out *ClusterDefinitionList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ClusterDefinition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterDefinitionList.
func (in *ClusterDefinitionList) DeepCopy() *ClusterDefinitionList {
	if in == nil {
		return nil
	}
	out := new(ClusterDefinitionList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClusterDefinitionList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterDefinitionProbe) DeepCopyInto(out *ClusterDefinitionProbe) {
	*out = *in
	if in.Commands != nil {
		in, out := &in.Commands, &out.Commands
		*out = new(ClusterDefinitionProbeCMDs)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterDefinitionProbe.
func (in *ClusterDefinitionProbe) DeepCopy() *ClusterDefinitionProbe {
	if in == nil {
		return nil
	}
	out := new(ClusterDefinitionProbe)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterDefinitionProbeCMDs) DeepCopyInto(out *ClusterDefinitionProbeCMDs) {
	*out = *in
	if in.Writes != nil {
		in, out := &in.Writes, &out.Writes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Queries != nil {
		in, out := &in.Queries, &out.Queries
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterDefinitionProbeCMDs.
func (in *ClusterDefinitionProbeCMDs) DeepCopy() *ClusterDefinitionProbeCMDs {
	if in == nil {
		return nil
	}
	out := new(ClusterDefinitionProbeCMDs)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterDefinitionProbes) DeepCopyInto(out *ClusterDefinitionProbes) {
	*out = *in
	if in.RunningProbe != nil {
		in, out := &in.RunningProbe, &out.RunningProbe
		*out = new(ClusterDefinitionProbe)
		(*in).DeepCopyInto(*out)
	}
	if in.StatusProbe != nil {
		in, out := &in.StatusProbe, &out.StatusProbe
		*out = new(ClusterDefinitionProbe)
		(*in).DeepCopyInto(*out)
	}
	if in.RoleProbe != nil {
		in, out := &in.RoleProbe, &out.RoleProbe
		*out = new(ClusterDefinitionProbe)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterDefinitionProbes.
func (in *ClusterDefinitionProbes) DeepCopy() *ClusterDefinitionProbes {
	if in == nil {
		return nil
	}
	out := new(ClusterDefinitionProbes)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterDefinitionSpec) DeepCopyInto(out *ClusterDefinitionSpec) {
	*out = *in
	if in.ComponentDefs != nil {
		in, out := &in.ComponentDefs, &out.ComponentDefs
		*out = make([]ClusterComponentDefinition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ConnectionCredential != nil {
		in, out := &in.ConnectionCredential, &out.ConnectionCredential
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Topologies != nil {
		in, out := &in.Topologies, &out.Topologies
		*out = make([]ClusterTopology, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterDefinitionSpec.
func (in *ClusterDefinitionSpec) DeepCopy() *ClusterDefinitionSpec {
	if in == nil {
		return nil
	}
	out := new(ClusterDefinitionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterDefinitionStatus) DeepCopyInto(out *ClusterDefinitionStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterDefinitionStatus.
func (in *ClusterDefinitionStatus) DeepCopy() *ClusterDefinitionStatus {
	if in == nil {
		return nil
	}
	out := new(ClusterDefinitionStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterTopology) DeepCopyInto(out *ClusterTopology) {
	*out = *in
	if in.Components != nil {
		in, out := &in.Components, &out.Components
		*out = make([]ClusterTopologyComponent, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Orders != nil {
		in, out := &in.Orders, &out.Orders
		*out = new(ClusterTopologyOrders)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterTopology.
func (in *ClusterTopology) DeepCopy() *ClusterTopology {
	if in == nil {
		return nil
	}
	out := new(ClusterTopology)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterTopologyComponent) DeepCopyInto(out *ClusterTopologyComponent) {
	*out = *in
	if in.Template != nil {
		in, out := &in.Template, &out.Template
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterTopologyComponent.
func (in *ClusterTopologyComponent) DeepCopy() *ClusterTopologyComponent {
	if in == nil {
		return nil
	}
	out := new(ClusterTopologyComponent)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterTopologyOrders) DeepCopyInto(out *ClusterTopologyOrders) {
	*out = *in
	if in.Provision != nil {
		in, out := &in.Provision, &out.Provision
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Terminate != nil {
		in, out := &in.Terminate, &out.Terminate
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Update != nil {
		in, out := &in.Update, &out.Update
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterTopologyOrders.
func (in *ClusterTopologyOrders) DeepCopy() *ClusterTopologyOrders {
	if in == nil {
		return nil
	}
	out := new(ClusterTopologyOrders)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CmdExecutorConfig) DeepCopyInto(out *CmdExecutorConfig) {
	*out = *in
	in.CommandExecutorEnvItem.DeepCopyInto(&out.CommandExecutorEnvItem)
	in.CommandExecutorItem.DeepCopyInto(&out.CommandExecutorItem)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CmdExecutorConfig.
func (in *CmdExecutorConfig) DeepCopy() *CmdExecutorConfig {
	if in == nil {
		return nil
	}
	out := new(CmdExecutorConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CommandExecutorEnvItem) DeepCopyInto(out *CommandExecutorEnvItem) {
	*out = *in
	if in.Env != nil {
		in, out := &in.Env, &out.Env
		*out = make([]corev1.EnvVar, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CommandExecutorEnvItem.
func (in *CommandExecutorEnvItem) DeepCopy() *CommandExecutorEnvItem {
	if in == nil {
		return nil
	}
	out := new(CommandExecutorEnvItem)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CommandExecutorItem) DeepCopyInto(out *CommandExecutorItem) {
	*out = *in
	if in.Command != nil {
		in, out := &in.Command, &out.Command
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Args != nil {
		in, out := &in.Args, &out.Args
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CommandExecutorItem.
func (in *CommandExecutorItem) DeepCopy() *CommandExecutorItem {
	if in == nil {
		return nil
	}
	out := new(CommandExecutorItem)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComponentConfigSpec) DeepCopyInto(out *ComponentConfigSpec) {
	*out = *in
	in.ComponentTemplateSpec.DeepCopyInto(&out.ComponentTemplateSpec)
	if in.Keys != nil {
		in, out := &in.Keys, &out.Keys
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.LegacyRenderedConfigSpec != nil {
		in, out := &in.LegacyRenderedConfigSpec, &out.LegacyRenderedConfigSpec
		*out = new(LegacyRenderedTemplateSpec)
		**out = **in
	}
	if in.AsEnvFrom != nil {
		in, out := &in.AsEnvFrom, &out.AsEnvFrom
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.InjectEnvTo != nil {
		in, out := &in.InjectEnvTo, &out.InjectEnvTo
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ReRenderResourceTypes != nil {
		in, out := &in.ReRenderResourceTypes, &out.ReRenderResourceTypes
		*out = make([]RerenderResourceType, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComponentConfigSpec.
func (in *ComponentConfigSpec) DeepCopy() *ComponentConfigSpec {
	if in == nil {
		return nil
	}
	out := new(ComponentConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComponentDefRef) DeepCopyInto(out *ComponentDefRef) {
	*out = *in
	if in.ComponentRefEnvs != nil {
		in, out := &in.ComponentRefEnvs, &out.ComponentRefEnvs
		*out = make([]ComponentRefEnv, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComponentDefRef.
func (in *ComponentDefRef) DeepCopy() *ComponentDefRef {
	if in == nil {
		return nil
	}
	out := new(ComponentDefRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComponentRefEnv) DeepCopyInto(out *ComponentRefEnv) {
	*out = *in
	if in.ValueFrom != nil {
		in, out := &in.ValueFrom, &out.ValueFrom
		*out = new(ComponentValueFrom)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComponentRefEnv.
func (in *ComponentRefEnv) DeepCopy() *ComponentRefEnv {
	if in == nil {
		return nil
	}
	out := new(ComponentRefEnv)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComponentTemplateSpec) DeepCopyInto(out *ComponentTemplateSpec) {
	*out = *in
	if in.DefaultMode != nil {
		in, out := &in.DefaultMode, &out.DefaultMode
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComponentTemplateSpec.
func (in *ComponentTemplateSpec) DeepCopy() *ComponentTemplateSpec {
	if in == nil {
		return nil
	}
	out := new(ComponentTemplateSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComponentValueFrom) DeepCopyInto(out *ComponentValueFrom) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComponentValueFrom.
func (in *ComponentValueFrom) DeepCopy() *ComponentValueFrom {
	if in == nil {
		return nil
	}
	out := new(ComponentValueFrom)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigTemplateExtension) DeepCopyInto(out *ConfigTemplateExtension) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigTemplateExtension.
func (in *ConfigTemplateExtension) DeepCopy() *ConfigTemplateExtension {
	if in == nil {
		return nil
	}
	out := new(ConfigTemplateExtension)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConsensusMember) DeepCopyInto(out *ConsensusMember) {
	*out = *in
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConsensusMember.
func (in *ConsensusMember) DeepCopy() *ConsensusMember {
	if in == nil {
		return nil
	}
	out := new(ConsensusMember)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConsensusSetSpec) DeepCopyInto(out *ConsensusSetSpec) {
	*out = *in
	in.StatefulSetSpec.DeepCopyInto(&out.StatefulSetSpec)
	in.Leader.DeepCopyInto(&out.Leader)
	if in.Followers != nil {
		in, out := &in.Followers, &out.Followers
		*out = make([]ConsensusMember, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Learner != nil {
		in, out := &in.Learner, &out.Learner
		*out = new(ConsensusMember)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConsensusSetSpec.
func (in *ConsensusSetSpec) DeepCopy() *ConsensusSetSpec {
	if in == nil {
		return nil
	}
	out := new(ConsensusSetSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CustomLabelSpec) DeepCopyInto(out *CustomLabelSpec) {
	*out = *in
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = make([]GVKResource, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CustomLabelSpec.
func (in *CustomLabelSpec) DeepCopy() *CustomLabelSpec {
	if in == nil {
		return nil
	}
	out := new(CustomLabelSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Exporter) DeepCopyInto(out *Exporter) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Exporter.
func (in *Exporter) DeepCopy() *Exporter {
	if in == nil {
		return nil
	}
	out := new(Exporter)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExporterConfig) DeepCopyInto(out *ExporterConfig) {
	*out = *in
	out.ScrapePort = in.ScrapePort
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExporterConfig.
func (in *ExporterConfig) DeepCopy() *ExporterConfig {
	if in == nil {
		return nil
	}
	out := new(ExporterConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GVKResource) DeepCopyInto(out *GVKResource) {
	*out = *in
	if in.Selector != nil {
		in, out := &in.Selector, &out.Selector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GVKResource.
func (in *GVKResource) DeepCopy() *GVKResource {
	if in == nil {
		return nil
	}
	out := new(GVKResource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HorizontalScalePolicy) DeepCopyInto(out *HorizontalScalePolicy) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HorizontalScalePolicy.
func (in *HorizontalScalePolicy) DeepCopy() *HorizontalScalePolicy {
	if in == nil {
		return nil
	}
	out := new(HorizontalScalePolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LegacyRenderedTemplateSpec) DeepCopyInto(out *LegacyRenderedTemplateSpec) {
	*out = *in
	out.ConfigTemplateExtension = in.ConfigTemplateExtension
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LegacyRenderedTemplateSpec.
func (in *LegacyRenderedTemplateSpec) DeepCopy() *LegacyRenderedTemplateSpec {
	if in == nil {
		return nil
	}
	out := new(LegacyRenderedTemplateSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LogConfig) DeepCopyInto(out *LogConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LogConfig.
func (in *LogConfig) DeepCopy() *LogConfig {
	if in == nil {
		return nil
	}
	out := new(LogConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MonitorConfig) DeepCopyInto(out *MonitorConfig) {
	*out = *in
	if in.Exporter != nil {
		in, out := &in.Exporter, &out.Exporter
		*out = new(ExporterConfig)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MonitorConfig.
func (in *MonitorConfig) DeepCopy() *MonitorConfig {
	if in == nil {
		return nil
	}
	out := new(MonitorConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PasswordConfig) DeepCopyInto(out *PasswordConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PasswordConfig.
func (in *PasswordConfig) DeepCopy() *PasswordConfig {
	if in == nil {
		return nil
	}
	out := new(PasswordConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PostStartAction) DeepCopyInto(out *PostStartAction) {
	*out = *in
	in.CmdExecutorConfig.DeepCopyInto(&out.CmdExecutorConfig)
	if in.ScriptSpecSelectors != nil {
		in, out := &in.ScriptSpecSelectors, &out.ScriptSpecSelectors
		*out = make([]ScriptSpecSelector, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PostStartAction.
func (in *PostStartAction) DeepCopy() *PostStartAction {
	if in == nil {
		return nil
	}
	out := new(PostStartAction)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProtectedVolume) DeepCopyInto(out *ProtectedVolume) {
	*out = *in
	if in.HighWatermark != nil {
		in, out := &in.HighWatermark, &out.HighWatermark
		*out = new(int)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProtectedVolume.
func (in *ProtectedVolume) DeepCopy() *ProtectedVolume {
	if in == nil {
		return nil
	}
	out := new(ProtectedVolume)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProvisionPolicy) DeepCopyInto(out *ProvisionPolicy) {
	*out = *in
	if in.Statements != nil {
		in, out := &in.Statements, &out.Statements
		*out = new(ProvisionStatements)
		**out = **in
	}
	if in.SecretRef != nil {
		in, out := &in.SecretRef, &out.SecretRef
		*out = new(ProvisionSecretRef)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProvisionPolicy.
func (in *ProvisionPolicy) DeepCopy() *ProvisionPolicy {
	if in == nil {
		return nil
	}
	out := new(ProvisionPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProvisionSecretRef) DeepCopyInto(out *ProvisionSecretRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProvisionSecretRef.
func (in *ProvisionSecretRef) DeepCopy() *ProvisionSecretRef {
	if in == nil {
		return nil
	}
	out := new(ProvisionSecretRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProvisionStatements) DeepCopyInto(out *ProvisionStatements) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProvisionStatements.
func (in *ProvisionStatements) DeepCopy() *ProvisionStatements {
	if in == nil {
		return nil
	}
	out := new(ProvisionStatements)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReplicationSetSpec) DeepCopyInto(out *ReplicationSetSpec) {
	*out = *in
	in.StatefulSetSpec.DeepCopyInto(&out.StatefulSetSpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReplicationSetSpec.
func (in *ReplicationSetSpec) DeepCopy() *ReplicationSetSpec {
	if in == nil {
		return nil
	}
	out := new(ReplicationSetSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScriptSpecSelector) DeepCopyInto(out *ScriptSpecSelector) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScriptSpecSelector.
func (in *ScriptSpecSelector) DeepCopy() *ScriptSpecSelector {
	if in == nil {
		return nil
	}
	out := new(ScriptSpecSelector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServicePort) DeepCopyInto(out *ServicePort) {
	*out = *in
	if in.AppProtocol != nil {
		in, out := &in.AppProtocol, &out.AppProtocol
		*out = new(string)
		**out = **in
	}
	out.TargetPort = in.TargetPort
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServicePort.
func (in *ServicePort) DeepCopy() *ServicePort {
	if in == nil {
		return nil
	}
	out := new(ServicePort)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceRefDeclaration) DeepCopyInto(out *ServiceRefDeclaration) {
	*out = *in
	if in.ServiceRefDeclarationSpecs != nil {
		in, out := &in.ServiceRefDeclarationSpecs, &out.ServiceRefDeclarationSpecs
		*out = make([]ServiceRefDeclarationSpec, len(*in))
		copy(*out, *in)
	}
	if in.Optional != nil {
		in, out := &in.Optional, &out.Optional
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceRefDeclaration.
func (in *ServiceRefDeclaration) DeepCopy() *ServiceRefDeclaration {
	if in == nil {
		return nil
	}
	out := new(ServiceRefDeclaration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceRefDeclarationSpec) DeepCopyInto(out *ServiceRefDeclarationSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceRefDeclarationSpec.
func (in *ServiceRefDeclarationSpec) DeepCopy() *ServiceRefDeclarationSpec {
	if in == nil {
		return nil
	}
	out := new(ServiceRefDeclarationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceSpec) DeepCopyInto(out *ServiceSpec) {
	*out = *in
	if in.Ports != nil {
		in, out := &in.Ports, &out.Ports
		*out = make([]ServicePort, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceSpec.
func (in *ServiceSpec) DeepCopy() *ServiceSpec {
	if in == nil {
		return nil
	}
	out := new(ServiceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StatefulSetSpec) DeepCopyInto(out *StatefulSetSpec) {
	*out = *in
	if in.LLUpdateStrategy != nil {
		in, out := &in.LLUpdateStrategy, &out.LLUpdateStrategy
		*out = new(appsv1.StatefulSetUpdateStrategy)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StatefulSetSpec.
func (in *StatefulSetSpec) DeepCopy() *StatefulSetSpec {
	if in == nil {
		return nil
	}
	out := new(StatefulSetSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StatelessSetSpec) DeepCopyInto(out *StatelessSetSpec) {
	*out = *in
	in.UpdateStrategy.DeepCopyInto(&out.UpdateStrategy)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StatelessSetSpec.
func (in *StatelessSetSpec) DeepCopy() *StatelessSetSpec {
	if in == nil {
		return nil
	}
	out := new(StatelessSetSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SwitchoverAction) DeepCopyInto(out *SwitchoverAction) {
	*out = *in
	if in.CmdExecutorConfig != nil {
		in, out := &in.CmdExecutorConfig, &out.CmdExecutorConfig
		*out = new(CmdExecutorConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.ScriptSpecSelectors != nil {
		in, out := &in.ScriptSpecSelectors, &out.ScriptSpecSelectors
		*out = make([]ScriptSpecSelector, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SwitchoverAction.
func (in *SwitchoverAction) DeepCopy() *SwitchoverAction {
	if in == nil {
		return nil
	}
	out := new(SwitchoverAction)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SwitchoverSpec) DeepCopyInto(out *SwitchoverSpec) {
	*out = *in
	if in.WithCandidate != nil {
		in, out := &in.WithCandidate, &out.WithCandidate
		*out = new(SwitchoverAction)
		(*in).DeepCopyInto(*out)
	}
	if in.WithoutCandidate != nil {
		in, out := &in.WithoutCandidate, &out.WithoutCandidate
		*out = new(SwitchoverAction)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SwitchoverSpec.
func (in *SwitchoverSpec) DeepCopy() *SwitchoverSpec {
	if in == nil {
		return nil
	}
	out := new(SwitchoverSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SystemAccountConfig) DeepCopyInto(out *SystemAccountConfig) {
	*out = *in
	in.ProvisionPolicy.DeepCopyInto(&out.ProvisionPolicy)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SystemAccountConfig.
func (in *SystemAccountConfig) DeepCopy() *SystemAccountConfig {
	if in == nil {
		return nil
	}
	out := new(SystemAccountConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SystemAccountSpec) DeepCopyInto(out *SystemAccountSpec) {
	*out = *in
	if in.CmdExecutorConfig != nil {
		in, out := &in.CmdExecutorConfig, &out.CmdExecutorConfig
		*out = new(CmdExecutorConfig)
		(*in).DeepCopyInto(*out)
	}
	out.PasswordConfig = in.PasswordConfig
	if in.Accounts != nil {
		in, out := &in.Accounts, &out.Accounts
		*out = make([]SystemAccountConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SystemAccountSpec.
func (in *SystemAccountSpec) DeepCopy() *SystemAccountSpec {
	if in == nil {
		return nil
	}
	out := new(SystemAccountSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VolumeProtectionSpec) DeepCopyInto(out *VolumeProtectionSpec) {
	*out = *in
	if in.Volumes != nil {
		in, out := &in.Volumes, &out.Volumes
		*out = make([]ProtectedVolume, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VolumeProtectionSpec.
func (in *VolumeProtectionSpec) DeepCopy() *VolumeProtectionSpec {
	if in == nil {
		return nil
	}
	out := new(VolumeProtectionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VolumeTypeSpec) DeepCopyInto(out *VolumeTypeSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VolumeTypeSpec.
func (in *VolumeTypeSpec) DeepCopy() *VolumeTypeSpec {
	if in == nil {
		return nil
	}
	out := new(VolumeTypeSpec)
	in.DeepCopyInto(out)
	return out
}
