# permissions for end users to edit clusterversions.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: src
    app.kubernetes.io/managed-by: kustomize
  name: clusterversion-editor-role
rules:
- apiGroups:
  - duanhui8.duangh
  resources:
  - clusterversions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - duanhui8.duangh
  resources:
  - clusterversions/status
  verbs:
  - get
