---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - duanhui8.duangh
  resources:
  - clusterdefinitions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - duanhui8.duangh
  resources:
  - clusterdefinitions/finalizers
  verbs:
  - update
- apiGroups:
  - duanhui8.duangh
  resources:
  - clusterdefinitions/status
  verbs:
  - get
  - patch
  - update
