apiVersion: duanhui8.duangh/v1
kind: Component
metadata:
  labels:
    app.kubernetes.io/name: src
    app.kubernetes.io/managed-by: kustomize
  name: component-sample
spec:
  # TODO(user): Add fields here
