apiVersion: duanhui8.duangh/v1
kind: ClusterVersion
metadata:
  labels:
    app.kubernetes.io/name: src
    app.kubernetes.io/managed-by: kustomize
  name: clusterversion-sample
spec:
  # TODO(user): Add fields here
